# Generated by Django 2.2.16 on 2022-03-07 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_mage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mage',
            new_name='image',
        ),
    ]
