# Generated by Django 2.2.16 on 2022-03-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20220307_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка необязательна', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
