# Generated by Django 2.2.16 on 2022-03-10 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20220310_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-user'], 'verbose_name': 'Избранный автор', 'verbose_name_plural': 'Избранные авторы'},
        ),
    ]
